---
version: 0.2
phases:
  install:
    commands:
      - echo "No dependencies to install"

  build:
    commands:
      - echo "📦 Zipping Lambda code"
      - zip -r ../function.zip .
  post_build:
    commands:
      - echo "Sync to S3 ($S3_BUCKET)"
      - aws s3 sync frontend/ "s3://$S3_BUCKET" --delete
      - |
        echo "Invalidate CloudFront"
        aws cloudfront create-invalidation \
          --distribution-id "$CF_DIST_ID" \
          --paths "/*"
      - echo "🚀 Updating Lambda function"
      - aws lambda update-function-code \
          --function-name resume-lynx-pardelle-comment \
          --zip-file fileb://function.zip \
          --publish
artifacts:
  files: 
    - function.zip
