---
version: 0.2

env:
  variables:
    LAMBDA_NAME: "resume-lynx-pardelle-comment"
    LAMBDA_DIR: "lambda"
    FRONTEND_DIR: "frontend"

phases:
  build:
    commands:
      - echo "Zipping Lambda code"
      - cd "$LAMBDA_DIR"
      - zip -r ../function.zip .
      - cd ..

  post_build:
    commands:
      - echo "Sync frontend to S3"
      - aws s3 sync "$FRONTEND_DIR/" "s3://$S3_BUCKET"
      - echo "Invalidate CloudFront"
      - aws cloudfront create-invalidation --distribution-id "$CF_DIST_ID" --paths "/*"
      - echo "Updating Lambda function"
      - aws lambda update-function-code --function-name "$LAMBDA_NAME" --zip-file fileb://function.zip --publish

artifacts:
  files:
    - function.zip
